version: '3.8'

services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: StandaloneDockerfile
    ports:
      - "3000:3000"  # NextJS
      - "4000:4000"  # NestJS
      - "5555:5555" # db studio
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./apps:/app/apps
    networks:
      - app-network
    command: >
      sh -c "echo DATABASE_URL=$${DATABASE_URL} &&
             ./start.sh"



  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
