version: '3.8'

services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - conf.ini
    environment:
      - POSTGRES_DB=your_database_name
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # NextJS
      - "4000:4000"  # NestJS
    depends_on:
      - postgres
    env_file:
      - conf.ini
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
    volumes:
      - ./apps:/app/apps
    networks:
      - app-network

  prisma-studio:
    build: .
    command: sh -c "cd apps/server && npx prisma studio"
    ports:
      - "5555:5555"
    depends_on:
      - postgres
    env_file:
      - conf.ini
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
